# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3d5bc4070afb4e9a0731129cddb1ac363db171d645e8d3d851b9709fa42da39d0ad6372e783e194eb7f07b673395fc254812295450103698fdd289be91112f2

test:
  secret_key_base: e0e17e77c181032cbd5c777d741b457b5c9cf5e4c12089932fb949a9ff364a5c0f6c6057b95712e9cfeaf4d3dcc9381120850b5fe6ddf0f09eb9550027cfc000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
